/**
 * hooks/input.ts — Prompt observation, classification, and agent-start timing.
 *
 * Subscribes to two pi events:
 *   `input`              — records every user prompt to the analytics sink.
 *   `before_agent_start` — captures the moment the agent starts processing
 *                          a prompt, used by T8 to compute `turn.started_at`.
 *
 * Both handlers are **observation-only**:
 * - `input` returns nothing (pi treats that as "continue" — no modification).
 * - `before_agent_start` returns nothing (no message injection needed).
 * Neither handler ever throws — errors are caught and console.warn'd so the
 * hot path inside pi is never blocked.
 *
 * ## Slash-command classification (best-effort)
 *
 * At the `input` event, pi has not yet resolved the slash-command type: it
 * hasn't checked extension commands, expanded skills, or matched templates.
 * We can only reliably detect skill-style commands (those with `:` in the
 * token after `/`, e.g. `/skill:foo`). All other slash commands are left as
 * `slash_kind: null` to avoid mis-classification. A future improvement could
 * cross-reference `pi.getCommands()` captured at registration time to
 * distinguish "extension" from "builtin" commands.
 */

import type { AnalyticsSink, PromptEvent } from "../sinks/types.ts";
import { newId } from "../sinks/types.ts";
import type { PrivacyMode } from "../redact/index.ts";
import {
  applyPrivacyMode,
  DEFAULT_RULES,
  compileUserPatterns,
} from "../redact/index.ts";
import type { HookContext, PiAPIStub, PiContextStub } from "./types.ts";
import { getActiveSessionId } from "./session-state.ts";

// ---------------------------------------------------------------------------
// Module-level state (per-session maps)
//
// Keyed by analytics session_id (a UUID generated by T6 at session_start).
// T8 reads these maps via the exported getter functions below.
// ---------------------------------------------------------------------------

/** session_id → analytics ID of the most recently emitted prompt. */
const latestPromptIdMap = new Map<string, string>();

/**
 * session_id → Unix ms timestamp captured at the last `before_agent_start`
 * event.  Used by T8 to measure user-perceived turn latency.
 */
const latestPromptStartTsMap = new Map<string, number>();

// ---------------------------------------------------------------------------
// Exported readers (consumed by T8 — hooks/turn.ts)
// ---------------------------------------------------------------------------

/**
 * Returns the analytics ID of the most recent prompt emitted for `sessionId`,
 * or null if no prompt has been seen yet in this session.
 *
 * T8 calls this at `turn_start` to populate `TurnStartEvent.prompt_id`.
 */
export function getLatestPromptId(sessionId: string): string | null {
  return latestPromptIdMap.get(sessionId) ?? null;
}

/**
 * Returns the Unix ms timestamp captured at the last `before_agent_start`
 * event for `sessionId`, or null if that event has not been seen yet.
 *
 * T8 uses this as `TurnStartEvent.started_at` for accurate latency
 * measurement: `before_agent_start` fires right after the user presses Enter,
 * before `turn_start`, giving a better "user → first token" signal.
 */
export function getLatestPromptStartTs(sessionId: string): number | null {
  return latestPromptStartTsMap.get(sessionId) ?? null;
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/**
 * Best-effort slash-command category classifier.
 *
 * @param tokenWithoutSlash - The slash command token with the leading `/`
 *   removed (e.g. "skill:foo", "usage", "new").
 *
 * Limitation: classification is best-effort. We only detect skill-style
 * commands (colon-separated). All other slash commands return null.
 */
function classifySlashKind(tokenWithoutSlash: string): PromptEvent["slash_kind"] {
  // Any token containing `:` after the `/` is a skill-style command.
  // Covers: /skill:foo, /template:bar, and similar colon-separated patterns.
  if (tokenWithoutSlash.includes(":")) return "skill";
  // Cannot reliably distinguish "extension" from "builtin" from "template"
  // at this stage — would require cross-referencing pi.getCommands().
  return null;
}

// ---------------------------------------------------------------------------
// register
// ---------------------------------------------------------------------------

/**
 * Register the `input` and `before_agent_start` event handlers.
 *
 * Called once by T15 (src/index.ts) during extension startup. Compiles user
 * redaction patterns from config at registration time and captures them in
 * the event-handler closures for efficiency (no recompilation per event).
 *
 * @param pi       - The pi ExtensionAPI (or structurally compatible stub).
 * @param sink     - The active analytics sink (MultiSink or single).
 * @param hookCtx  - Shared hook context with config and exec function (T15).
 */
export function register(
  pi: PiAPIStub,
  sink: AnalyticsSink,
  hookCtx: HookContext,
): void {
  // Compile user-supplied redaction patterns once at registration time so
  // each event handler can reuse the compiled rules without re-parsing config.
  const userRules = compileUserPatterns(hookCtx.config.privacy.redactPatterns);
  const allRules = [...DEFAULT_RULES, ...userRules];

  // ── input ─────────────────────────────────────────────────────────────────
  //
  // Fired after extension commands are checked, before skill/template
  // expansion. Sees the raw input text (e.g. "/skill:foo" unexpanded).

  pi.on("input", async (rawEvent: unknown, piCtx: PiContextStub) => {
    try {
      const ev = rawEvent as {
        text: string;
        images?: unknown[];
        source: string;
      };

      // Look up the analytics session ID via session-state registry (T6).
      // Returns null for ephemeral sessions or if session_start hasn't fired yet.
      const sessionFile = piCtx.sessionManager.getSessionFile();
      const sessionId = getActiveSessionId(sessionFile);

      const promptId = newId();
      const ts = Date.now();

      // --- Slash-command extraction ---
      let command: string | null = null;
      let slashKind: PromptEvent["slash_kind"] = null;
      if (ev.text.startsWith("/")) {
        // Take the first whitespace-delimited token (e.g. "/skill:foo" from
        // "/skill:foo extra args here")
        command = ev.text.split(/\s+/)[0] ?? null;
        if (command) {
          slashKind = classifySlashKind(command.slice(1)); // strip leading "/"
        }
      }

      // --- Privacy-aware text handling ---
      // storePrompts is "full" | "hashed" | "none" — all are valid PrivacyMode
      // values (PrivacyMode also includes "summary" but prompts don't use it).
      const mode = hookCtx.config.privacy.storePrompts as PrivacyMode;
      const stored = applyPrivacyMode(ev.text, mode, allRules);

      // Build the event: text and redacted are only included when the privacy
      // mode stores text ("full" or "summary"). For "hashed"/"none" modes,
      // `stored` has no `text` property, so the spread contributes nothing.
      const promptEvent: PromptEvent = {
        kind: "prompt",
        ts,
        id: promptId,
        session_id: sessionId ?? "unknown",
        source: ev.source,
        command,
        slash_kind: slashKind,
        text_len: stored.length,
        text_sha256: stored.sha256,
        image_count: ev.images?.length ?? 0,
      };

      // Include redacted text only when the mode stores it.
      if (stored.mode === "full" || stored.mode === "summary") {
        promptEvent.text = stored.text;
        promptEvent.redacted = stored.redacted;
      }

      // Stash this prompt's ID so T8 can link the upcoming turn to it.
      if (sessionId) {
        latestPromptIdMap.set(sessionId, promptId);
      }

      sink.write(promptEvent);
    } catch (err) {
      console.warn("[analytics:hooks/input] error in `input` handler:", err);
    }
    // Returning nothing is equivalent to { action: "continue" } per pi docs.
  });

  // ── before_agent_start ────────────────────────────────────────────────────
  //
  // Fired after `input` (and any skill/template expansion), immediately before
  // the agent loop begins. We record the timestamp here — not at `turn_start`
  // — because it more accurately reflects when the user submitted their prompt.

  pi.on(
    "before_agent_start",
    async (_rawEvent: unknown, piCtx: PiContextStub) => {
      try {
        const sessionFile = piCtx.sessionManager.getSessionFile();
        const sessionId = getActiveSessionId(sessionFile);
        if (sessionId) {
          // Capture agent-start timestamp. T8 reads this via
          // getLatestPromptStartTs() to compute the `started_at` for turns.
          latestPromptStartTsMap.set(sessionId, Date.now());
        }
      } catch (err) {
        console.warn(
          "[analytics:hooks/input] error in `before_agent_start` handler:",
          err,
        );
      }
      // No return value — this handler does not inject messages.
    },
  );
}
