/**
 * session-state.ts — In-process session state registry for all hook modules.
 *
 * All hooks in this extension share a single process with pi, so a
 * module-level Map is the simplest consistent store — no IPC, no DB round-
 * trips needed for hot-path lookups.
 *
 * ## Key scheme
 *
 * Entries are keyed by session file path (from
 * `ctx.sessionManager.getSessionFile()`). When pi runs without a session file
 * (ephemeral sessions — rare, but possible in `-p` / print mode), we use the
 * EPHEMERAL_KEY sentinel so the map never stores `undefined`.
 *
 * Other hook modules (T7–T10) look up the session ID via:
 *   `getActiveSessionId(ctx.sessionManager.getSessionFile())`
 *
 * ## Concurrency
 *
 * Pi is single-threaded (Node.js event loop). No locking is needed.
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/**
 * Per-session state captured at `session_start` and updated by
 * `session_patch` events (after async git capture resolves).
 */
export type SessionSnapshot = {
  /** The analytics session ID generated by T6 at session_start. */
  sessionId: string;
  /**
   * HEAD SHA captured at session start (null until git capture resolves).
   * Used by session_shutdown to compute the diff summary.
   */
  headShaStart: string | null;
  /**
   * Branch name at session start (null until git capture resolves).
   * Stored for informational purposes; shutdown always re-reads via
   * captureRepoSnapshot to get the final branch.
   */
  branchStart: string | null;
  /** Working directory at session start, used for git calls at shutdown. */
  cwd: string;
};

// ---------------------------------------------------------------------------
// Registry
// ---------------------------------------------------------------------------

/**
 * Sentinel key used when the session has no backing file (ephemeral session).
 * Exported so tests can assert on it if needed.
 */
export const EPHEMERAL_KEY = "~ephemeral~";

/** Module-level registry — one entry per active session. */
const registry = new Map<string, SessionSnapshot>();

/**
 * Normalise `sessionFile` to a stable map key, substituting the sentinel
 * for null (ephemeral sessions).
 */
function stateKey(sessionFile: string | null): string {
  return sessionFile ?? EPHEMERAL_KEY;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Register a new session or replace an existing one under `sessionFile`.
 * Called by T6 at `session_start`.
 */
export function setSession(
  sessionFile: string | null,
  snapshot: SessionSnapshot,
): void {
  registry.set(stateKey(sessionFile), snapshot);
}

/**
 * Return the analytics session ID for the given pi session file, or null if
 * the session has not been registered (e.g. called before session_start).
 *
 * Used by T7–T10 to obtain the session ID without direct access to T6's
 * internal state.
 */
export function getActiveSessionId(sessionFile: string | null): string | null {
  return registry.get(stateKey(sessionFile))?.sessionId ?? null;
}

/**
 * Remove the session state entry. Called by T6 at `session_shutdown` after
 * final events have been emitted.
 */
export function clearSession(sessionFile: string | null): void {
  registry.delete(stateKey(sessionFile));
}

/**
 * Return the full snapshot for the given session, or undefined if not
 * registered.
 *
 * T6 uses this at `session_shutdown` to retrieve `headShaStart` and `cwd`.
 */
export function getSnapshot(sessionFile: string | null): SessionSnapshot | undefined {
  return registry.get(stateKey(sessionFile));
}

/**
 * Apply a partial update to an existing snapshot.
 * Called by T6 after `captureRepoSnapshot` resolves to store the git fields
 * that are later needed at `session_shutdown`.
 *
 * No-op if the session has already been cleared.
 */
export function patchSnapshot(
  sessionFile: string | null,
  patch: Partial<SessionSnapshot>,
): void {
  const existing = registry.get(stateKey(sessionFile));
  if (existing) {
    Object.assign(existing, patch);
  }
}
