/**
 * pricing/lookup.ts — Shared multi-provider model pricing lookup.
 *
 * Rates are loaded at module-init time from rates.json, which is generated by
 * `scripts/generate-pricing.ts` from curated YAML sources in pricing-sources/.
 * Run that generator before building this package (scripts/install.sh does so
 * automatically).
 *
 * PUBLIC API
 *   lookupRates(modelId)       → ModelRates | undefined
 *   computeCostMicros(params)  → CostBreakdown
 *
 * This module is intentionally dependency-free beyond the Node built-ins and
 * the generated rates.json artifact.
 */

import ratesData from "./rates.json";

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

/** Per-model list-price rates, all in USD per million tokens (MTok). */
export interface ModelRates {
  /** USD per million input tokens at list price. */
  inputPerMTokUSD: number;
  /** USD per million output tokens at list price. */
  outputPerMTokUSD: number;
  /** USD per million cache-read tokens at list price. */
  cacheReadPerMTokUSD: number;
  /** USD per million cache-write (creation) tokens at list price. */
  cacheWritePerMTokUSD: number;
}

/**
 * Cost breakdown in integer micro-dollars (1 USD = 1_000_000 micros).
 *
 * Integer representation eliminates IEEE-754 drift in aggregations. The store
 * CHECK constraint enforces:
 *   cost_total_micros = cost_input_micros + cost_output_micros
 *                     + cost_cache_read_micros + cost_cache_write_micros
 * so callers must sum the four breakdown fields when writing to the store.
 *
 * `costSource` is `"writer"` when rates were found and applied, `"unknown"`
 * when the model is not in the pricing table (all cost fields are 0).
 */
export interface CostBreakdown {
  costInputMicros: number;
  costOutputMicros: number;
  costCacheReadMicros: number;
  costCacheWriteMicros: number;
  /** `"writer"` | `"unknown"` */
  costSource: "writer" | "unknown";
}

/** Input to computeCostMicros. */
export interface CostInput {
  /** Model identifier as reported by the harness (e.g. "claude-sonnet-4-5"). */
  modelId: string | null | undefined;
  /** Tokens in the prompt/input. */
  inputTokens: number;
  /** Tokens in the model's response. */
  outputTokens: number;
  /** Cache-read (cache-hit) tokens. Default 0. */
  cacheReadTokens?: number;
  /** Cache-write (cache-creation) tokens. Default 0. */
  cacheWriteTokens?: number;
}

// ---------------------------------------------------------------------------
// Internal lookup tables
//
// Built once at module load from rates.json. We maintain three maps for the
// three-step resolution used by lookupRates():
//   1. exactById     — canonical model id → rates
//   2. exactByAlias  — alias string → rates
//   3. allIds        — sorted list of all canonical ids for prefix matching
// ---------------------------------------------------------------------------

// Shape of a model entry in rates.json.
interface RateEntry {
  id: string;
  provider: string;
  aliases: string[];
  inputPerMTokUSD: number;
  outputPerMTokUSD: number;
  cacheReadPerMTokUSD: number;
  cacheWritePerMTokUSD: number;
}

const exactById = new Map<string, ModelRates>();
const exactByAlias = new Map<string, ModelRates>();

function toModelRates(entry: RateEntry): ModelRates {
  return {
    inputPerMTokUSD: entry.inputPerMTokUSD,
    outputPerMTokUSD: entry.outputPerMTokUSD,
    cacheReadPerMTokUSD: entry.cacheReadPerMTokUSD,
    cacheWritePerMTokUSD: entry.cacheWritePerMTokUSD,
  };
}

// Populate maps from the generated rates data.
for (const entry of ratesData.models as RateEntry[]) {
  const rates = toModelRates(entry);
  exactById.set(entry.id, rates);
  for (const alias of entry.aliases ?? []) {
    exactByAlias.set(alias, rates);
  }
}

// Sorted canonical ids, used for prefix matching.
const allIds: string[] = Array.from(exactById.keys()).sort();

// Per-process set of model IDs already warned about (suppresses repeat noise).
const _warnedIds = new Set<string>();

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Look up pricing rates for a model ID.
 *
 * Resolution order (matches the Claude Code writer's algorithm):
 *   1. Exact match in the canonical ID table.
 *   2. Exact match in the alias table.
 *   3. Prefix match: any canonical ID that starts with `modelId + "-"`.
 *   4. Iteratively strip the last dash-segment from `modelId` and repeat
 *      steps 1–3 until the string is exhausted.
 *
 * Returns `undefined` and emits a one-time `console.warn` for unknown models
 * so callers can record `cost_source = 'unknown'` rather than silently
 * storing zeros.
 */
export function lookupRates(modelId: string): ModelRates | undefined {
  let candidate = modelId;

  while (candidate.length > 0) {
    // Step 1: exact canonical-id match.
    const byId = exactById.get(candidate);
    if (byId !== undefined) return byId;

    // Step 2: exact alias match.
    const byAlias = exactByAlias.get(candidate);
    if (byAlias !== undefined) return byAlias;

    // Step 3: prefix match — candidate is a prefix of a canonical id.
    const prefix = candidate + "-";
    const prefixHit = allIds.find((id) => id.startsWith(prefix));
    if (prefixHit !== undefined) return exactById.get(prefixHit);

    // Step 4: strip the last dash-segment and retry.
    const lastDash = candidate.lastIndexOf("-");
    if (lastDash === -1) break;
    candidate = candidate.slice(0, lastDash);
  }

  // Unknown model — warn once per process per ID.
  if (!_warnedIds.has(modelId)) {
    _warnedIds.add(modelId);
    console.warn(
      `[token-tally/store] Unknown model ID for pricing: "${modelId}". ` +
        "Recording cost_source=unknown for messages from this model.",
    );
  }
  return undefined;
}

/**
 * Compute the list-price cost breakdown for a single LLM usage record.
 *
 * Returns `costSource: "unknown"` with all-zero cost fields when the model is
 * not in the pricing table. Callers should store such rows with
 * `cost_source = 'unknown'` so readers can exclude them from headline totals.
 *
 * All output costs are integer micro-dollars (1 USD = 1_000_000 micros).
 */
export function computeCostMicros(params: CostInput): CostBreakdown {
  const { modelId, inputTokens, outputTokens } = params;
  const cacheReadTokens = params.cacheReadTokens ?? 0;
  const cacheWriteTokens = params.cacheWriteTokens ?? 0;

  if (!modelId) {
    return zeroCostBreakdown();
  }

  const rates = lookupRates(modelId);
  if (rates === undefined) {
    return zeroCostBreakdown();
  }

  return {
    costInputMicros: tokensToMicros(inputTokens, rates.inputPerMTokUSD),
    costOutputMicros: tokensToMicros(outputTokens, rates.outputPerMTokUSD),
    costCacheReadMicros: tokensToMicros(cacheReadTokens, rates.cacheReadPerMTokUSD),
    costCacheWriteMicros: tokensToMicros(cacheWriteTokens, rates.cacheWritePerMTokUSD),
    costSource: "writer",
  };
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/**
 * Convert a token count to integer micro-dollars given a rate in USD/MTok.
 *
 * Formula: round(tokens × rateUSD/MTok)
 *   = round(tokens × rateUSD / 1_000_000 × 1_000_000)
 *   = round(tokens × rateUSD)
 */
function tokensToMicros(tokens: number, ratePerMTokUSD: number): number {
  return Math.round(tokens * ratePerMTokUSD);
}

function zeroCostBreakdown(): CostBreakdown {
  return {
    costInputMicros: 0,
    costOutputMicros: 0,
    costCacheReadMicros: 0,
    costCacheWriteMicros: 0,
    costSource: "unknown",
  };
}
