/**
 * types.ts — Canonical shared contracts for the pi analytics extension.
 *
 * This file is the single source of truth for:
 *   - AnalyticsConfig     (mirrors config.json)
 *   - AnalyticsEvent      (discriminated union of every event kind)
 *   - AnalyticsSink       (interface all sinks implement)
 *   - MultiSink           (fan-out helper)
 *   - Type guards         (isSessionEvent, isTurnEvent, isToolEvent)
 *   - newId()             (shared UUID generator)
 *
 * **RULE: No other file may modify this file.**
 * Hooks emit events; sinks consume them; both import only from this module.
 *
 * T3 (redact module) exports `RedactionHits` and `StoredText`.  We import
 * them here with a type-only import so events can carry redaction metadata
 * inline.  If T3 has not finished yet when you run `tsc --noEmit`, you will
 * see "Cannot find module '../redact'" — that is expected during Wave 1
 * parallel execution; re-verify once all Wave 1 tasks are complete.
 *
 * Design note on `storeToolOutputs: "size-only"`:
 * The config allows "size-only" for tool outputs, which is not a valid
 * `PrivacyMode` in T3's privacy.ts (which uses "none"|"hashed"|"summary"|"full").
 * We keep "size-only" as a distinct literal in `AnalyticsConfig.privacy`
 * because it has a unique meaning (record byte count, drop all text — not even
 * a hash is needed).  The NdjsonSink (T5) handles this case separately before
 * calling `applyPrivacyMode`.
 */

// ---------------------------------------------------------------------------
// Redaction metadata (sourced from T3 — type-only import avoids runtime dep)
// ---------------------------------------------------------------------------

import type { RedactionHits } from "../redact/index.js";

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

/**
 * Mirrors the structure of config.json exactly.  All fields are required; the
 * extension entrypoint merges user config over these defaults before use.
 */
export type AnalyticsConfig = {
  local: {
    /** Whether the local SQLite + NDJSON storage is active. */
    enabled: boolean;
    /** Absolute or ~-prefixed path to the SQLite database file. */
    dbPath: string;
    /** Directory for per-day NDJSON append logs. */
    rawLogDir: string;
  };
  privacy: {
    /**
     * Controls how raw prompt text is stored.
     *   "full"   — store after redaction
     *   "hashed" — store sha256 + length only (default)
     *   "none"   — store neither text nor hash
     */
    storePrompts: "full" | "hashed" | "none";
    /**
     * Controls how tool input arguments are stored.
     *   "full"    — store after redaction
     *   "summary" — store first ~200 chars after redaction (default)
     *   "none"    — drop all arg content
     */
    storeToolArgs: "full" | "summary" | "none";
    /**
     * Controls how tool output text is stored.
     *   "full"      — store after redaction
     *   "size-only" — record byte count only, drop text (default)
     *   "none"      — drop even the byte count
     */
    storeToolOutputs: "full" | "size-only" | "none";
    /** User-supplied regex patterns (strings) compiled and added to default rules. */
    redactPatterns: string[];
  };
  git: {
    /** Enable git/PR capture at session boundaries and bash-tool detection. */
    enabled: boolean;
    /** Whether to call `gh pr view` at session_start to find the current PR. */
    fetchPR: boolean;
    /** Timeout in ms for `gh` CLI calls (keeps startup fast). */
    ghTimeoutMs: number;
  };
};

// ---------------------------------------------------------------------------
// Event variants — one per observable pi event / database table
// ---------------------------------------------------------------------------

// ── Session ─────────────────────────────────────────────────────────────────

/**
 * Emitted at session_start.  Git fields start null and are patched
 * asynchronously via SessionPatchEvent once `captureRepoSnapshot` resolves.
 * The SQLite sink upserts on `id` so the patch safely fills in the blanks.
 */
export type SessionStartEvent = {
  kind: "session_start";
  ts: number;
  /** Stable identifier for this session, generated by the hook. */
  id: string;
  parent_session_id: string | null;
  parent_session_file: string | null;
  started_at: number;
  cwd: string;
  pi_version: string;
  hostname: string;
  // git fields — initially null, filled by SessionPatchEvent
  repo_root: string | null;
  repo_remote: string | null;
  repo_owner: string | null;
  repo_name: string | null;
  branch_start: string | null;
  head_sha_start: string | null;
  dirty_at_start: number | null;
};

/**
 * Asynchronous update that fills in git fields after `captureRepoSnapshot`
 * resolves.  SqliteSink UPDATE-OR-IGNOREs on session_id.
 * T6 emits this shortly after SessionStartEvent to avoid blocking the session
 * start path on git I/O.
 */
export type SessionPatchEvent = {
  kind: "session_patch";
  ts: number;
  session_id: string;
  repo_root: string | null;
  repo_remote: string | null;
  repo_owner: string | null;
  repo_name: string | null;
  branch_start: string | null;
  head_sha_start: string | null;
  dirty_at_start: number | null;
};

/**
 * Emitted at session_shutdown.  Git end-state is captured synchronously
 * before this event fires.
 */
export type SessionEndEvent = {
  kind: "session_end";
  ts: number;
  session_id: string;
  ended_at: number;
  branch_end: string | null;
  head_sha_end: string | null;
  exit_reason: string | null;
};

// ── Branch ──────────────────────────────────────────────────────────────────

/**
 * Emitted when a `git checkout` / `git switch` is detected in a bash tool call
 * or (future) via external branch change detection.
 */
export type BranchTransitionEvent = {
  kind: "branch_transition";
  ts: number;
  session_id: string;
  turn_id: string | null;
  from_branch: string;
  to_branch: string;
};

// ── PR ───────────────────────────────────────────────────────────────────────

/**
 * Emitted when a PR is linked to a session.  Reason values and confidence
 * thresholds mirror PLAN.md *Multi-session → single PR linking*.
 */
export type PrAssociationEvent = {
  kind: "pr_association";
  ts: number;
  session_id: string;
  repo_remote: string;
  pr_number: number;
  pr_url: string;
  confidence: number;
  reason:
    | "commit-in-pr"
    | "ancestor-of-pr"
    | "branch-match"
    | "files-overlap"
    | "preceding-window";
};

// ── Prompt ───────────────────────────────────────────────────────────────────

/**
 * Emitted on `input`.  Raw prompt text is never stored by default
 * (`storePrompts = "hashed"`).  The `redacted` counter tracks any secrets
 * scrubbed by the hooks before the event is written.
 */
export type PromptEvent = {
  kind: "prompt";
  ts: number;
  id: string;
  session_id: string;
  source: string;
  /** First token if the input started with `/`, otherwise null. */
  command: string | null;
  /** Best-effort classification of the slash command type. */
  slash_kind: "extension" | "skill" | "template" | "builtin" | null;
  text_len: number;
  text_sha256: string;
  image_count: number;
  /**
   * Only present when `storePrompts = "full"` or `"summary"`.
   * Already redacted by the hook before inclusion.
   */
  text?: string;
  /** Redaction hits accumulated while processing this prompt, if any. */
  redacted?: RedactionHits;
};

// ── Turn ─────────────────────────────────────────────────────────────────────

/**
 * Emitted when a turn begins.  Model/thinking fields are included here
 * (denormalized) because `turns` is the primary query surface for these.
 */
export type TurnStartEvent = {
  kind: "turn_start";
  ts: number;
  id: string;
  session_id: string;
  prompt_id: string;
  /** 0-based index of this turn within its prompt. */
  idx: number;
  started_at: number;
  model_id: string | null;
  provider: string | null;
  thinking_level: string | null;
};

/**
 * Emitted when a turn completes.  The SQLite sink updates the existing row
 * (inserted at turn_start) with the end-state fields.
 */
export type TurnEndEvent = {
  kind: "turn_end";
  ts: number;
  turn_id: string;
  session_id: string;
  ended_at: number;
  model_id: string | null;
  provider: string | null;
  thinking_level: string | null;
  stop_reason: string | null;
};

/**
 * Emitted on `after_provider_response`.  Contains HTTP status and
 * normalised rate-limit headers.  SqliteSink updates the in-flight turn row.
 */
export type ProviderResponseEvent = {
  kind: "provider_response";
  ts: number;
  turn_id: string;
  session_id: string;
  http_status: number | null;
  /** Remaining request quota from `anthropic-ratelimit-requests-remaining` etc. */
  ratelimit_remaining: number | null;
  /** Unix ms until rate-limit resets (from `retry-after` or `*-reset`). */
  ratelimit_reset: number | null;
};

// ── LLM message ──────────────────────────────────────────────────────────────

/**
 * Emitted on `message_end` for `role === "assistant"`.  Carries the full
 * token usage and cost breakdown from `event.message.usage`.
 */
export type LlmMessageEvent = {
  kind: "llm_message";
  ts: number;
  id: string;
  turn_id: string;
  session_id: string;
  role: string;
  input_tokens: number;
  output_tokens: number;
  /** Tokens read from the prompt cache. */
  cache_read_tokens: number;
  /** Tokens written to the prompt cache. */
  cache_write_tokens: number;
  cost_input: number;
  cost_output: number;
  cost_cache_read: number;
  cost_cache_write: number;
  cost_total: number;
  /** Prompt-cache write retention observed on the provider request, if known. */
  cache_write_retention: "5m" | "1h" | null;
  time_to_first_token_ms: number | null;
  total_duration_ms: number | null;
  stop_reason: string | null;
  /**
   * The model id used for this response (e.g. "claude-sonnet-4-5").
   * Sourced from AssistantMessage.model — always present for real responses.
   * Nullable for NDJSON replay compatibility with pre-002 events.
   */
  model_id: string | null;
  /**
   * The provider name (e.g. "anthropic", "openai").
   * Nullable for NDJSON replay compatibility with pre-002 events.
   */
  provider: string | null;
};

// ── Tool calls ───────────────────────────────────────────────────────────────

/**
 * Emitted on `tool_execution_end`.  `tool_call_id` is the pi-assigned
 * identifier that correlates start/end events (parallel tools may interleave).
 */
export type ToolCallEvent = {
  kind: "tool_call";
  ts: number;
  id: string;
  turn_id: string;
  session_id: string;
  /** The pi-assigned correlation ID for this tool invocation. */
  tool_call_id: string;
  name: string;
  started_at: number;
  ended_at: number;
  duration_ms: number;
  is_error: boolean;
  input_bytes: number;
  output_bytes: number;
  error_kind: string | null;
  /** Secrets scrubbed from args/output before this event was emitted. */
  redacted?: RedactionHits;
};

/**
 * Emitted for each file that a tool touched.  `op` is the operation type.
 * When `sensitive = true`, the path triggered a sensitive-path rule in T3 and
 * content was dropped entirely; only the path and byte count are recorded.
 */
export type FileTouchedEvent = {
  kind: "file_touched";
  ts: number;
  tool_call_id: string;
  session_id: string;
  path: string;
  op: "read" | "write" | "edit" | "bash-derived";
  bytes: number;
  /**
   * True when `pathIsSensitive(path)` returned true — content was suppressed
   * regardless of `storeToolOutputs` setting.
   */
  sensitive: boolean;
  redacted?: RedactionHits;
};

/**
 * Emitted when bash-detect (T12) identifies a git or gh side-effect.
 * Used by T15/T13 to trigger eager PR linking and commit capture.
 * This is a marker event — it does not map to a dedicated DB table but is
 * persisted in NDJSON for replay / debugging.
 */
export type ToolSideEffectEvent = {
  kind: "tool_side_effect";
  ts: number;
  session_id: string;
  turn_id: string;
  /** Which side-effect was detected. */
  effect: "git-push" | "gh-pr-create";
  remote?: string;
  branch?: string;
};

// ── Commits ───────────────────────────────────────────────────────────────────

/**
 * Emitted when a `git commit` is observed (via bash-detect or session_shutdown
 * diff summary).  SHA may be null if captured before the command completed.
 */
export type CommitMadeEvent = {
  kind: "commit_made";
  ts: number;
  session_id: string;
  turn_id: string | null;
  sha: string;
  subject: string;
  files_changed: number;
  insertions: number;
  deletions: number;
};

// ── Model / thinking-level ───────────────────────────────────────────────────

/**
 * Emitted on `model_select`.  Also stored denormalized on turns so the
 * standalone event is mainly for the models tab aggregation.
 */
export type ModelSelectEvent = {
  kind: "model_select";
  ts: number;
  session_id: string;
  model_id: string;
  provider: string | null;
};

/**
 * Emitted on `thinking_level_select`.
 */
export type ThinkingLevelSelectEvent = {
  kind: "thinking_level_select";
  ts: number;
  session_id: string;
  turn_id: string | null;
  thinking_level: string;
};

// ── Resources ────────────────────────────────────────────────────────────────

/**
 * Emitted when a skill, template, or preset is loaded.
 * Mirrors the `resource_usage` table.
 */
export type ResourceUsedEvent = {
  kind: "resource_used";
  ts: number;
  session_id: string;
  label: string;
  kind_: string; // named `kind_` to avoid collision with the discriminant `kind`
  name: string;
};

// ---------------------------------------------------------------------------
// Full discriminated union
// ---------------------------------------------------------------------------

export type AnalyticsEvent =
  | SessionStartEvent
  | SessionPatchEvent
  | SessionEndEvent
  | BranchTransitionEvent
  | PrAssociationEvent
  | PromptEvent
  | TurnStartEvent
  | TurnEndEvent
  | ProviderResponseEvent
  | LlmMessageEvent
  | ToolCallEvent
  | FileTouchedEvent
  | ToolSideEffectEvent
  | CommitMadeEvent
  | ModelSelectEvent
  | ThinkingLevelSelectEvent
  | ResourceUsedEvent;

// ---------------------------------------------------------------------------
// Sink interface
// ---------------------------------------------------------------------------

/**
 * Every storage backend (SQLite, NDJSON, future OTLP) implements this
 * interface.  `write` is synchronous so the hot path never awaits storage —
 * sinks decide internally whether to buffer or write inline.
 */
export interface AnalyticsSink {
  /** Open connections, create directories, run migrations. */
  init(config: AnalyticsConfig): Promise<void>;
  /**
   * Record one event.  MUST NOT throw — callers do not try/catch this.
   * Implementations should catch their own errors and console.warn.
   */
  write(event: AnalyticsEvent): void;
  /** Flush any pending buffers.  No-op for synchronous sinks. */
  flush(): Promise<void>;
  /** Close connections / file handles gracefully. */
  close(): Promise<void>;
}

// ---------------------------------------------------------------------------
// MultiSink — fan-out helper
// ---------------------------------------------------------------------------

/**
 * Fans out write/flush/close to multiple sinks in order.
 * Errors from individual sinks are caught and console.warn'd so a broken
 * sink (e.g. full disk on NDJSON) cannot kill the SQLite path or the hot
 * path of pi itself.
 */
export class MultiSink implements AnalyticsSink {
  private readonly sinks: AnalyticsSink[];

  constructor(sinks: AnalyticsSink[]) {
    this.sinks = sinks;
  }

  async init(config: AnalyticsConfig): Promise<void> {
    for (const sink of this.sinks) {
      try {
        await sink.init(config);
      } catch (err) {
        console.warn("[analytics:MultiSink] init failed on a sink:", err);
      }
    }
  }

  write(event: AnalyticsEvent): void {
    for (const sink of this.sinks) {
      try {
        sink.write(event);
      } catch (err) {
        console.warn("[analytics:MultiSink] write failed on a sink:", err);
      }
    }
  }

  async flush(): Promise<void> {
    for (const sink of this.sinks) {
      try {
        await sink.flush();
      } catch (err) {
        console.warn("[analytics:MultiSink] flush failed on a sink:", err);
      }
    }
  }

  async close(): Promise<void> {
    for (const sink of this.sinks) {
      try {
        await sink.close();
      } catch (err) {
        console.warn("[analytics:MultiSink] close failed on a sink:", err);
      }
    }
  }
}

// ---------------------------------------------------------------------------
// Type guards
// ---------------------------------------------------------------------------

/**
 * True for events that map to the `sessions` table (start, patch, end).
 * Useful for sinks that maintain in-memory session state.
 */
export function isSessionEvent(
  e: AnalyticsEvent,
): e is SessionStartEvent | SessionPatchEvent | SessionEndEvent {
  return (
    e.kind === "session_start" ||
    e.kind === "session_patch" ||
    e.kind === "session_end"
  );
}

/**
 * True for events that map to the `turns` table or its related
 * `after_provider_response` row.
 */
export function isTurnEvent(
  e: AnalyticsEvent,
): e is TurnStartEvent | TurnEndEvent | ProviderResponseEvent {
  return (
    e.kind === "turn_start" ||
    e.kind === "turn_end" ||
    e.kind === "provider_response"
  );
}

/**
 * True for events that relate to tool execution or file I/O.
 */
export function isToolEvent(
  e: AnalyticsEvent,
): e is ToolCallEvent | FileTouchedEvent | ToolSideEffectEvent {
  return (
    e.kind === "tool_call" ||
    e.kind === "file_touched" ||
    e.kind === "tool_side_effect"
  );
}

/**
 * True for events that map to the `llm_messages` table.
 */
export function isLlmMessageEvent(e: AnalyticsEvent): e is LlmMessageEvent {
  return e.kind === "llm_message";
}

/**
 * True for events that relate to git activity (commits, branches, PRs).
 */
export function isGitEvent(
  e: AnalyticsEvent,
): e is CommitMadeEvent | BranchTransitionEvent | PrAssociationEvent {
  return (
    e.kind === "commit_made" ||
    e.kind === "branch_transition" ||
    e.kind === "pr_association"
  );
}

// ---------------------------------------------------------------------------
// ID generator
// ---------------------------------------------------------------------------

/**
 * Generates a new random UUID v4.  Re-exported here so all modules that need
 * an ID import from a single place rather than each calling `crypto.randomUUID`.
 */
export function newId(): string {
  return crypto.randomUUID();
}
